POST http://{{host}}/forms
Content-Type: application/json

{
  "name": "Order task",
  "type": {
    "module": "prodactivv",
    "name": "Task"
  },
  "fields": [
    {
      "label": "Task name",
      "modelField": {
        "name": "name",
        "type": {
          "module": "primitives",
          "name": "String"
        },
        "constraints": [
          "Required"
        ],
        "multiplicity": "SINGULAR"
      }
    },
    {
      "label": "Task Description",
      "modelField": {
        "name": "description",
        "type": {
          "module": "primitives",
          "name": "String"
        },
        "constraints": [],
        "multiplicity": "SINGULAR"
      }
    },
    {
      "label": "Ordered",
      "modelField": {
        "name": "orderedOn",
        "type": {
          "module": "primitives",
          "name": "LocalDateTime"
        },
        "constraints": [],
        "multiplicity": "SINGULAR"
      }
    },
    {
      "label": "Deadline",
      "modelField": {
        "name": "deadline",
        "type": {
          "module": "primitives",
          "name": "LocalDateTime"
        },
        "constraints": [],
        "multiplicity": "SINGULAR"
      }
    },
    {
      "label": "Orderer",
      "modelField": {
        "name": "orderer",
        "type": {
          "module": "organization",
          "name": "AppUser"
        },
        "constraints": [
          "Required",
          "NotInsertable"
        ],
        "multiplicity": "SINGULAR"
      }
    },
    {
      "label": "Performer",
      "modelField": {
        "name": "performer",
        "type": {
          "module": "organization",
          "name": "AppUser"
        },
        "constraints": [
          "Required",
          "NotInsertable"
        ],
        "multiplicity": "SINGULAR"
      }
    },
    {
      "label": "Customer",
      "modelField": {
        "name": "customer",
        "type": {
          "module": "organization",
          "name": "Customer"
        },
        "constraints": [
          "NotInsertable"
        ],
        "multiplicity": "SINGULAR"
      }
    },
    {
      "label": "Project",
      "modelField": {
        "name": "project",
        "type": {
          "module": "prodactivvity",
          "name": "Project"
        },
        "constraints": [],
        "multiplicity": "SINGULAR"
      }
    }
  ]
}